module Evergreen.Migrate.V22 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Types
import Evergreen.V22.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V22.Types.FrontendModel Evergreen.V22.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V22.Types.BackendModel Evergreen.V22.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V22.Types.FrontendMsg Evergreen.V22.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V22.Types.ToBackend Evergreen.V22.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V22.Types.BackendMsg Evergreen.V22.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V22.Types.ToFrontend Evergreen.V22.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V22.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , urlInput = old.urlInput
    , status = old.status |> migrate_Types_AuditStatus
    , history = old.history |> List.map migrate_Types_HistoryEntry
    , historyQuery = old.historyQuery
    , now = old.now
    , excludedIssues = old.excludedIssues
    , promptCopied = old.promptCopied
    }


migrate_Types_AuditReport : Evergreen.V1.Types.AuditReport -> Evergreen.V22.Types.AuditReport
migrate_Types_AuditReport old =
    { url = old.url
    , finalUrl = old.finalUrl
    , scannedAt = old.scannedAt
    , perceivedLoadMs = old.perceivedLoadMs
    , totalTestMs = old.totalTestMs
    , score = old.score
    , passed = old.passed
    , warnings = old.warnings
    , errors = old.errors
    , categories = old.categories |> List.map migrate_Types_Category
    }


migrate_Types_AuditStatus : Evergreen.V1.Types.AuditStatus -> Evergreen.V22.Types.AuditStatus
migrate_Types_AuditStatus old =
    case old of
        Evergreen.V1.Types.Idle ->
            Evergreen.V22.Types.Idle

        Evergreen.V1.Types.Running p0 ->
            Evergreen.V22.Types.Running p0

        Evergreen.V1.Types.Done p0 ->
            Evergreen.V22.Types.Done (p0 |> migrate_Types_AuditReport)

        Evergreen.V1.Types.Failed p0 ->
            Evergreen.V22.Types.Failed p0


migrate_Types_Category : Evergreen.V1.Types.Category -> Evergreen.V22.Types.Category
migrate_Types_Category old =
    { name = old.name
    , checks = old.checks |> List.map migrate_Types_Check
    }


migrate_Types_Check : Evergreen.V1.Types.Check -> Evergreen.V22.Types.Check
migrate_Types_Check old =
    { id = old.id
    , name = old.name
    , severity = old.severity |> migrate_Types_Severity
    , summary = old.summary
    , affectedResources = old.affectedResources
    , howToFix = old.howToFix
    , extra = old.extra
    }


migrate_Types_HistoryEntry : Evergreen.V1.Types.HistoryEntry -> Evergreen.V22.Types.HistoryEntry
migrate_Types_HistoryEntry old =
    { url = old.url
    , finalUrl = old.finalUrl
    , scannedAt = old.scannedAt
    , score = old.score
    , passed = old.passed
    , warnings = old.warnings
    , errors = old.errors
    , report = old.report |> migrate_Types_AuditReport
    }


migrate_Types_Page : Evergreen.V1.Types.Page -> Evergreen.V22.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V1.Types.Home ->
            Evergreen.V22.Types.Home

        Evergreen.V1.Types.HistoryPage ->
            Evergreen.V22.Types.HistoryPage


migrate_Types_Severity : Evergreen.V1.Types.Severity -> Evergreen.V22.Types.Severity
migrate_Types_Severity old =
    case old of
        Evergreen.V1.Types.Pass ->
            Evergreen.V22.Types.Pass

        Evergreen.V1.Types.Warning ->
            Evergreen.V22.Types.Warning

        Evergreen.V1.Types.Errored ->
            Evergreen.V22.Types.Errored
