module Evergreen.Migrate.V26 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V22.Types
import Evergreen.V26.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V22.Types.FrontendModel -> ModelMigration Evergreen.V26.Types.FrontendModel Evergreen.V26.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V22.Types.BackendModel -> ModelMigration Evergreen.V26.Types.BackendModel Evergreen.V26.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V22.Types.FrontendMsg -> MsgMigration Evergreen.V26.Types.FrontendMsg Evergreen.V26.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V22.Types.ToBackend -> MsgMigration Evergreen.V26.Types.ToBackend Evergreen.V26.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V22.Types.BackendMsg -> MsgMigration Evergreen.V26.Types.BackendMsg Evergreen.V26.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V22.Types.ToFrontend -> MsgMigration Evergreen.V26.Types.ToFrontend Evergreen.V26.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V22.Types.FrontendModel -> Evergreen.V26.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , urlInput = old.urlInput
    , status = old.status |> migrate_Types_AuditStatus
    , history = old.history |> List.map migrate_Types_HistoryEntry
    , historyQuery = old.historyQuery
    , now = old.now
    , excludedIssues = old.excludedIssues
    , promptCopied = old.promptCopied
    , hoveredDot = Nothing
    }


migrate_Types_AuditReport : Evergreen.V22.Types.AuditReport -> Evergreen.V26.Types.AuditReport
migrate_Types_AuditReport old =
    { url = old.url
    , finalUrl = old.finalUrl
    , scannedAt = old.scannedAt
    , perceivedLoadMs = old.perceivedLoadMs
    , totalTestMs = old.totalTestMs
    , score = old.score
    , passed = old.passed
    , warnings = old.warnings
    , errors = old.errors
    , categories = old.categories |> List.map migrate_Types_Category
    }


migrate_Types_AuditStatus : Evergreen.V22.Types.AuditStatus -> Evergreen.V26.Types.AuditStatus
migrate_Types_AuditStatus old =
    case old of
        Evergreen.V22.Types.Idle ->
            Evergreen.V26.Types.Idle

        Evergreen.V22.Types.Running p0 ->
            Evergreen.V26.Types.Running p0

        Evergreen.V22.Types.Done p0 ->
            Evergreen.V26.Types.Done (p0 |> migrate_Types_AuditReport)

        Evergreen.V22.Types.Failed p0 ->
            Evergreen.V26.Types.Failed p0


migrate_Types_Category : Evergreen.V22.Types.Category -> Evergreen.V26.Types.Category
migrate_Types_Category old =
    { name = old.name
    , checks = old.checks |> List.map migrate_Types_Check
    }


migrate_Types_Check : Evergreen.V22.Types.Check -> Evergreen.V26.Types.Check
migrate_Types_Check old =
    { id = old.id
    , name = old.name
    , severity = old.severity |> migrate_Types_Severity
    , summary = old.summary
    , affectedResources = old.affectedResources
    , howToFix = old.howToFix
    , extra = old.extra
    }


migrate_Types_FrontendMsg : Evergreen.V22.Types.FrontendMsg -> Evergreen.V26.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V22.Types.UrlClicked p0 ->
            Evergreen.V26.Types.UrlClicked p0

        Evergreen.V22.Types.UrlChanged p0 ->
            Evergreen.V26.Types.UrlChanged p0

        Evergreen.V22.Types.NoOpFrontendMsg ->
            Evergreen.V26.Types.NoOpFrontendMsg

        Evergreen.V22.Types.UrlInputChanged p0 ->
            Evergreen.V26.Types.UrlInputChanged p0

        Evergreen.V22.Types.AnalyzeClicked ->
            Evergreen.V26.Types.AnalyzeClicked

        Evergreen.V22.Types.HistoryQueryChanged p0 ->
            Evergreen.V26.Types.HistoryQueryChanged p0

        Evergreen.V22.Types.OpenHistoryEntry p0 ->
            Evergreen.V26.Types.OpenHistoryEntry (p0 |> migrate_Types_HistoryEntry)

        Evergreen.V22.Types.ToggleIssue p0 ->
            Evergreen.V26.Types.ToggleIssue p0

        Evergreen.V22.Types.CopyFixPrompt p0 ->
            Evergreen.V26.Types.CopyFixPrompt p0

        Evergreen.V22.Types.PromptCopiedMsg ->
            Evergreen.V26.Types.PromptCopiedMsg

        Evergreen.V22.Types.Tick p0 ->
            Evergreen.V26.Types.Tick p0


migrate_Types_HistoryEntry : Evergreen.V22.Types.HistoryEntry -> Evergreen.V26.Types.HistoryEntry
migrate_Types_HistoryEntry old =
    { url = old.url
    , finalUrl = old.finalUrl
    , scannedAt = old.scannedAt
    , score = old.score
    , passed = old.passed
    , warnings = old.warnings
    , errors = old.errors
    , report = old.report |> migrate_Types_AuditReport
    }


migrate_Types_Page : Evergreen.V22.Types.Page -> Evergreen.V26.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V22.Types.Home ->
            Evergreen.V26.Types.Home

        Evergreen.V22.Types.HistoryPage ->
            Evergreen.V26.Types.HistoryPage

        Evergreen.V22.Types.SitePage p0 ->
            Evergreen.V26.Types.SitePage p0


migrate_Types_Severity : Evergreen.V22.Types.Severity -> Evergreen.V26.Types.Severity
migrate_Types_Severity old =
    case old of
        Evergreen.V22.Types.Pass ->
            Evergreen.V26.Types.Pass

        Evergreen.V22.Types.Warning ->
            Evergreen.V26.Types.Warning

        Evergreen.V22.Types.Errored ->
            Evergreen.V26.Types.Errored
